config/routes.rb
Rails.application.routes.draw do

  resources :locations do
    resources :products
  end

  resources :categories
  resources :products
  resources :sessions, only: [:new, :create, :destroy]

  get '/signup' => 'users#new', as: 'signup'
  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'
  post '/rent/:id' => 'products#rent', as: 'rent'

  resources :users do
    resources :products
  end

  resources :charges

  resources :users do
    resources :profiles

    get 'page/index'

  end
  root 'landing#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<section class= "categories container" id= "shop">
	<tbody>
		<% @categories.each do |category| %>
		<tr>
			<a href= "/charges#show" class= "categories"> <td><%= category.name %></td> </a>
		</tr>
		<% end %>
	</tbody>
</table>

<%= link_to 'New Category', new_category_path, class: 'new_category b' %>
</section>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h1> <%=@category.name%> Products </h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Owner</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @category.products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.formatted_price %></td>
        <td><%= product.description %></td>
        <td><%= product.owner_id %></td>
        <td><%= link_to 'Show', product %></td>
        <% if current_user.id == product.owner_id %>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <% end %>
        <% if current_user.id != product.owner_id %>
        <td><%= link_to 'Pay', new_charge_path(:product_id =>  product.id) %>
        <% end %>
        <td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %> |
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>