config/routes.rb
Rails.application.routes.draw do

  resources :locations do
    resources :products
  end

  resources :categories
  resources :products
  resources :sessions, only: [:new, :create, :destroy]

  get '/signup' => 'users#new', as: 'signup'
  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'
  post '/rent/:id' => 'products#rent', as: 'rent'

  resources :users do
    resources :products
  end

  resources :charges

  resources :users do
    resources :profiles

    get 'page/index'

  end
  root 'landing#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :products, through: :users
  has_many :users
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  belongs_to :location, through: :users
  belongs_to :category

  validates :name, :description, :category_id, presence: true
  validates :price, numericality: { only_integer: true, greater_than: 0 }

  def formatted_price
    price_in_dollars = price.to_f
    format("$%.2f", price_in_dollars)
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  validates_presence_of :bio
  validates_presence_of :member_id

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

validates 	:first_name,
			presence: true
validates 	:last_name,
			presence: true
validates 	:email,
			presence: true,
			uniqueness: true,
			format: {
			with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
			}


has_one :profile
has_many :products, dependent: :destroy
belongs_to :location



	def to_s
		"#{first_name}#{last_name}"
	end
end

app/controllers/charges_controller.rb
  class ChargesController < ApplicationController

   def index
   end

   def new
     @product = Product.find(params[:product_id])
     @amount = @product.price
   end

   def create
     # Amount in cents
     @product = Product.find(3)
     @amount = @product.price


     customer = Stripe::Customer.create(
       :email => params[:stripeEmail],
       :source  => params[:stripeToken]
       )

     charge = Stripe::Charge.create(
       :customer    => customer.id,
       :amount      => @amount,
       :description => 'Rails Stripe customer',
       :currency    => 'usd'
       )

   rescue Stripe::CardError => e
     flash[:error] = e.message
     redirect_to new_charge_path
   end
 end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @location = Location.all
  end

  def create
    @location = Location.find_or_create_by(location_params)
    current_user.update(location: @location)
  end

  def new
    @location = Location.new
  end

  def show
    @location = Location.find(params[:id])
  end

  private

  def location_params
    params.require(:location).permit(:city, :region, :country)
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end
  # RENT products

  def rent
    @product = Product.find(params[:id])
    @product.renter_id = current_user.id
    @product.save
    redirect_to products_path

  end

  # POST /products
  def create
    @product = Product.new(product_params)
    @product.owner_id = current_user.id
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :user_id, :renter_id, :category_id, :id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :set_user
  before_action :authenticate

  # GET /profiles
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  def show
  end

  # GET /profiles/new
  def new
    @profile = @user.build_profile
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  def create
    @profile = @user.create_profile(profile_params)

    if @profile.save
      redirect_to member_profile_path(@user, @profile), notice: 'Profile was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /profiles/1
  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /profiles/1
  def destroy
    @profile.destroy
    redirect_to profiles_url, notice: 'Profile was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def set_member
      @user = User.find(params[:user_id])
    end

    # Only allow a trusted parameter "white list" through.
    def profile_params
      params.require(:profile).permit(:bio, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email (params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to user_path(current_user.id), notice: 'Logged in!'
  	else
  		render :new
  	end
  end

  def destroy
  session[:user_id] = nil
  redirect_to '/login', notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:create, :new]
  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_page_index_path(current_user.id), notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def full_name
    @user.first_name + " " + @user.last_name
  end

  def email
    @user.email
  end
end

app/views/locations/create.html.erb
<h1>Location#create</h1>
<p>Find me in app/views/location/create.html.erb</p>

app/views/locations/index.html.erb
<h1 class="page-header", style="text-align: center">Pick Your Location</h1>
<h4 style="text-align: center">And find your gear</h4>
<table class="table">
  <thead>
    <tr>
      <th style="text-align: center">City</th>
      <th style="text-align: center">State/Region</th>
      <th style="text-align: center">Country</th>
      <th style="text-align: center">Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @location.each do |location| %>
      <tr>
        <td style="text-align: center"><%= location.city %></td>
        <td style="text-align: center"><%= location.region %></td>
        <td style="text-align: center"><%= location.country %></td>
        <td style="text-align: center"><%= link_to 'Show', location_path(location) %></td>
        <td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/locations/new.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/show.html.erb
<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th> </th>
      <th>email</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @location.users.each do |locationuser| %>
      <tr>
        <td><%= locationuser.first_name %></td>
        <td><%= locationuser.last_name %></td>
        <td><%= locationuser.email %></td>
        <td><%= link_to 'Show', locationuser %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select :category_id, options_for_select( Category.all.collect{ |c| [c.name, c.id] })
 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Select A Rental</h1>
<%= link_to 'Profile', user_page_index_path(current_user) %>


<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Owner</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.formatted_price %></td>
        <td><%= product.description %></td>
        <td><%= product.owner_id %></td>
        <td><%= Category.find(product.category_id).name %></td>
        <td class="btn btn-primary btn-margin"><%= link_to 'Show', product %></td>
        <% if current_user.id == product.owner_id %>
        <td class="btn btn-warning btn-margin"><%= link_to 'Edit', edit_product_path(product) %></td>
        <% end %>
        <% if current_user.id == product.owner_id %>
        <td class="btn btn-danger btn-margin"><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% if current_user.id != product.owner_id %>
        <td class="btn btn-success btn-margin" ><%= link_to 'Pay', new_charge_path(:product_id =>  product.id) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Profile', user_page_index_path(current_user) %> | <%= link_to 'Products', products_path %>

app/views/products/show.html.erb
<%= link_to 'Profile', user_page_index_path(current_user) %><p id="notice"><%= notice %></p>


<%= p @location.products %>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.formatted_price %>
</p>

<p>
  <%= @product.description %>
</p>
<br>
<img class="show_image" src="http://www.hittingthegreen.com/wp-content/uploads/2011/11/prosimmon_golf_x9_clubs1.jpg" alt="google/images">

<p>
  <%= @product.owner_id %>
</p>

<p>
  <strong>Renter:</strong>
  <%= @product.renter_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>
<% if current_user.id == @product.owner_id %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<% end %>
<td class="btn btn-primary"><%= link_to 'Back', products_path %></td>

app/views/profiles/_form.html.erb
<%= form_for[@user, @profile do |f| %>
  end
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Bio</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.bio %></td>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

app/views/profiles/show.html.erb
<p>
  <strong>Bio:</strong>
  <%= @profile.bio %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user_id %>
</p>

app/views/users/_form.html.erb
<div class="full-screen">
  <div class="box">
    <h1 class="header">Sign Up</h1>
    <div class="content">

<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_page_index_path(current_user) %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p><%=full_name%></p>

<p><%= email %></p>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @user.products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= product.description %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Update Your Location', new_location_path %>
<%= link_to 'Rent A Product', location_path %> |
<%= link_to 'Post A Product', new_product_path %> |

<%= link_to 'Edit', edit_user_path(@user) %>