config/routes.rb
Rails.application.routes.draw do

  resources :locations do
    resources :products
  end

  resources :categories
  resources :products
  resources :sessions, only: [:new, :create, :destroy]

  get '/signup' => 'users#new', as: 'signup'
  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'
  post '/rent/:id' => 'products#rent', as: 'rent'

  resources :users do
    resources :products
  end

  resources :charges

  resources :users do
    resources :profiles

    get 'page/index'

  end
  root 'landing#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :products, through: :users
  has_many :users
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  belongs_to :location, through: :users
  belongs_to :category

  validates :name, :description, :category_id, presence: true
  validates :price, numericality: { only_integer: true, greater_than: 0 }

  def formatted_price
    price_in_dollars = price.to_f
    format("$%.2f", price_in_dollars)
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  validates_presence_of :bio
  validates_presence_of :member_id

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

validates 	:first_name,
			presence: true
validates 	:last_name,
			presence: true
validates 	:email,
			presence: true,
			uniqueness: true,
			format: {
			with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
			}


has_one :profile
has_many :products, dependent: :destroy
belongs_to :location



	def to_s
		"#{first_name}#{last_name}"
	end
end

app/controllers/charges_controller.rb
  class ChargesController < ApplicationController

   def index
   end

   def new
     @product = Product.find(params[:product_id])
     @amount = @product.price
   end

   def create
     # Amount in cents
     @product = Product.find(3)
     @amount = @product.price


     customer = Stripe::Customer.create(
       :email => params[:stripeEmail],
       :source  => params[:stripeToken]
       )

     charge = Stripe::Charge.create(
       :customer    => customer.id,
       :amount      => @amount,
       :description => 'Rails Stripe customer',
       :currency    => 'usd'
       )

   rescue Stripe::CardError => e
     flash[:error] = e.message
     redirect_to new_charge_path
   end
 end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end
  # RENT products

  def rent
    @product = Product.find(params[:id])
    @product.renter_id = current_user.id
    @product.save
    redirect_to products_path

  end

  # POST /products
  def create
    @product = Product.new(product_params)
    @product.owner_id = current_user.id
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :user_id, :renter_id, :category_id, :id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :set_user
  before_action :authenticate

  # GET /profiles
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  def show
  end

  # GET /profiles/new
  def new
    @profile = @user.build_profile
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  def create
    @profile = @user.create_profile(profile_params)

    if @profile.save
      redirect_to member_profile_path(@user, @profile), notice: 'Profile was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /profiles/1
  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /profiles/1
  def destroy
    @profile.destroy
    redirect_to profiles_url, notice: 'Profile was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def set_member
      @user = User.find(params[:user_id])
    end

    # Only allow a trusted parameter "white list" through.
    def profile_params
      params.require(:profile).permit(:bio, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email (params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to user_path(current_user.id), notice: 'Logged in!'
  	else
  		render :new
  	end
  end

  def destroy
  session[:user_id] = nil
  redirect_to '/login', notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:create, :new]
  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_page_index_path(current_user.id), notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def full_name
    @user.first_name + " " + @user.last_name
  end

  def email
    @user.email
  end
end

app/views/charges/create.html.erb
<!DOCTYPE html>
    <html>

      <head>

        <meta charset="utf-8">

        <link type="text/css" rel="stylesheet" href="charges.scss">

        <title>Payment Complete Page</title>

      </head>

      <body>

        <!-- <div id="header">This is the header</div> -->

      <div id="container">

        <div id="center" class="column">

          <div class="Receipt">
            <div class="circle">
               <h2>You paid $ <strong><%= @amount %></strong></h2>
            </div>
            <h2>Thank you, Enjoy !</h2>
            <p>A full receipt has been<br /> sent to zane@pedro.com</p>
            <button class="action-btn" type="button">
              <%= link_to 'Return to Home Page', user_page_index_url(current_user) %>
            </button>
          </div>

        </div>

        <div id="left" class="column">This Is The Nav</div>

        <div id="right" class="column">This Is The Aside</div>

      </div>

        <!-- <div id="footer">This is a footer</div> -->

      </body>

    </html>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <p>Your Rental Cost:</p>
    <label class="amount">
      <span>Amount: <%= @amount %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Rental"
          data-amount="<%= @amount * 100%>>"
          data-locale="auto"></script>
<% end %>

app/views/landing/index.html.erb
<header id="first">
	
	
	<h1 class="cursive">PostUp</h1>
	<hr>
	<a href="categories#categories" id="toggleVideo" data-toggle="collapse" class="btn btn-primary btn-xl">Rent a Product</a> <br/>
	<a href="products/new" class="btn btn-primary btn-xl page-scroll">Post a Product</a></hr>
	<br/>
	<a class="btn btn-primary btn-xl" href="#">Profile</a>
	
</header> 