config/routes.rb
Rails.application.routes.draw do

  resources :locations do
    resources :products
  end

  resources :categories
  resources :products
  resources :sessions, only: [:new, :create, :destroy]

  get '/signup' => 'users#new', as: 'signup'
  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'
  post '/rent/:id' => 'products#rent', as: 'rent'

  resources :users do
    resources :products
  end

  resources :charges

  resources :users do
    resources :profiles

    get 'page/index'

  end
  root 'landing#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :products, through: :users
  has_many :users
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  belongs_to :location, through: :users
  belongs_to :category

  validates :name, :description, :category_id, presence: true
  validates :price, numericality: { only_integer: true, greater_than: 0 }

  def formatted_price
    price_in_dollars = price.to_f
    format("$%.2f", price_in_dollars)
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  validates_presence_of :bio
  validates_presence_of :member_id

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

validates 	:first_name,
			presence: true
validates 	:last_name,
			presence: true
validates 	:email,
			presence: true,
			uniqueness: true,
			format: {
			with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
			}


has_one :profile
has_many :products, dependent: :destroy
belongs_to :location



	def to_s
		"#{first_name}#{last_name}"
	end
end

app/controllers/charges_controller.rb
  class ChargesController < ApplicationController

   def index
   end

   def new
     @product = Product.find(params[:product_id])
     @amount = @product.price
   end

   def create
     # Amount in cents
     @product = Product.find(3)
     @amount = @product.price


     customer = Stripe::Customer.create(
       :email => params[:stripeEmail],
       :source  => params[:stripeToken]
       )

     charge = Stripe::Charge.create(
       :customer    => customer.id,
       :amount      => @amount,
       :description => 'Rails Stripe customer',
       :currency    => 'usd'
       )

   rescue Stripe::CardError => e
     flash[:error] = e.message
     redirect_to new_charge_path
   end
 end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end
  # RENT products

  def rent
    @product = Product.find(params[:id])
    @product.renter_id = current_user.id
    @product.save
    redirect_to products_path

  end

  # POST /products
  def create
    @product = Product.new(product_params)
    @product.owner_id = current_user.id
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :user_id, :renter_id, :category_id, :id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:create, :new]
  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_page_index_path(current_user.id), notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def full_name
    @user.first_name + " " + @user.last_name
  end

  def email
    @user.email
  end
end

app/views/layouts/application.html.erb
 <!DOCTYPE html>
  <html>
  <head>
  <title>PostUp</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
 </head>
 <body>
 <div id="user_header">
   <% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", logout_path %>
   <% else %>
  <%= link_to "Sign Up", signup_path %> or
  <%= link_to "Log In", login_path %>
   <% end %>
 </div>
 
 <% flash.each do |key, value| %>
   <%= content_tag(:div, class: "alert alert-#{key}") do %>
   <p><%= value %></p>
   <% end %>
   <% end %>
 
 <%= yield %>
 
 </body>
 </html>
 

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>

  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>

  <script type="text/javascript">
  Stripe.setPublishableKey('pk_test_kkObgdeQ1aPeWPvBF0t9wPDk');
  </script>


</head>

<body>


  <%= yield %>
</body>
</html>

app/views/page/index.html.erb
<div class="row well">
  <div class="pull-left">

    <div id="user_header">
      <% if current_user %>
    	Logged in as <%= current_user.email %>.
    	<%= link_to "Log Out", logout_path %>
      <% else %>
    	<%= link_to "Sign Up", signup_path %> or
    	<%= link_to "Log In", login_path %>
      <% end %>
    </div>

  </div>
  <div class="pull-right">
    <button class="btn btn-primary" type="button">Home</button>
    <button class="btn btn-primary" type="button">Profile</button>
    <button class="btn btn-primary" type="button">Settings</button>
    <button class="btn btn-primary" type="button">Log Out</button>
  </div>
</div>

<div class="well">
  <div class="row">
    <div class="col-md-3">
      <div class="gearbox">
        <h1 class="text-center lead gear-header">Profile</h1>
        <%= link_to 'MESSAGES', products_path, :class => "btn btn-info" %>
        <%= link_to 'POST UP',new_product_path , :class => "btn btn-info" %>
        <%= link_to 'RENT',products_path, :class => "btn btn-info" %>
        <%= link_to 'BACK', users_path, :class => "btn btn-info" %>
      </div>
      <div class="gearbox">
        <h3 class="text-center lead gear-header">My Garage</h3>
        <button class="btn btn-primary" type="button">Compare Rentals</button>
        <button class="btn btn-primary" type="button">Reviews</button>
        <button class="btn btn-primary" type="button">Past Rentals</button>
        <button class="btn btn-primary" type="button">Log Out</button>
      </div>
    </div>

    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-body">
          <section >
            <img class="img-circle img-responsive center-block" style="width: 200px; height: 200px" src="https://media.licdn.com/media/AAEAAQAAAAAAAAIvAAAAJDMzMmM5YjVlLTIxNWYtNGRkZS04NzFiLWYwMzk1ZTk4NDExNQ.jpg" alt="Adamn Sandlers/Linkedin" />
          </section>
          <br>
          <br>
          <div class="well text-center">

            <p>Username: @Billy@Madison.co<p>
            <p>Location: Miami<p>
            <p>Member Since: 2015<p>
            <p>Born & raised in Miami So I know the city very well! I live with my Girlfriend Alyssa and our dog Ziggy! We are very Adventurous and love all outdoor activities! Please check out our gear and see if you need anything for rent! We have awsome Stand Up Paddle boards, a few bikes and even Golf Clubs! Feel free to Message us even if you just want some information on Miami!<p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="col-md-12">
        <h3 class="text-center lead gear-header">Local Rentals</h3>
        <div class="row">
          <a href="http://localhost:3000/products">
            <img class="img-responsive img-rounded custom-image" src="https://s-media-cache-ak0.pinimg.com/736x/07/a9/bd/07a9bdf5a946a60b6f08fdac2881982f.jpg" alt="google/images">
          </a>

          <span class="badge custom-badge">$40</span>
        </div>
        <div class="row">
          <a href="http://localhost:3000/products">
            <img class="img-responsive img-rounded custom-image" src="http://www.golfclubhybrid.com/img//2010/02/history-of-golf-clubs.jpg" alt="google/images">
          </a>

          <span class="badge custom-badge" >$25</span>
        </div>
        <div class="row">
          <a href="http://localhost:3000/products">
            <img class="img-responsive img-rounded custom-image" src=" https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRtKp4oswA9309tmaKiS06IJ42T--boVz0KbimKdIUH8K6pKHbe" alt="google/images">
          </a>

          <span class="badge custom-badge">$32</span>
        </div>
      </div>
    </div>
  </div>
</div>